<?php 

$cars = [
    [
        'id_auto' => 1,
        'codice_telaio' => 'R53VY57TKMA18VVZD',
        'marca' => 'Ferrari',
        'modello' => 'Portofino',
        'numero_porte' => 3,
        'cilindrata' => 3.9,
        'targa' => 'ES345NM',
        'km' => 120000,
        'anno' => 2018,
        'costo' => 240000,
        'colore' => 'rosso',
        'kilowatt' => 456,
        'peso' => 1664,
        'patente' => 'B',
        'foto' => 'https://immagini.alvolante.it/sites/default/files/styles/image_gallery_big/public/news_galleria/2020/09/ferrari-portofino-m_2.jpg?itok=tDFjw6Ty',
        'carburante' => 'benzina'
    ],
    [
        'id_auto' => 2,
        'codice_telaio' => 'LL8LL5FVJGW70180W',
        'marca' => 'Fiat',
        'modello' => 'Panda',
        'numero_porte' => 5,
        'cilindrata' => 1.2,
        'targa' => 'RF565SN',
        'km' => 145654,
        'anno' => 2017,
        'costo' => 8400,
        'colore' => 'bianca',
        'kilowatt' => 54,
        'peso' => 1684,
        'patente' => 'B',
        'foto' => 'https://cdn.euroncap.com/media/41884/fiat-panda-359-235.201811191201216873.jpg',
        'carburante' => 'benzina'
    ],
    [
        'id_auto' => 3,
        'codice_telaio' => 'IAWG4MPBM9XOFSNSD',
        'marca' => 'Porsche',
        'modello' => 'Carrera',
        'numero_porte' => 5,
        'cilindrata' => 3,
        'targa' => 'ED234TF',
        'km' => 80234,
        'anno' => 2014,
        'costo' => 34900,
        'colore' => 'grigia',
        'kilowatt' => 283,
        'peso' => 1754,
        'patente' => 'B',
        'foto' => 'https://files.porsche.com/filestore/image/multimedia/none/992-c2s-modelexplorer-04/normal/e6983412-cf38-11eb-80d9-005056bbdc38;sS;twebp/porsche-normal.webp',
        'carburante' => 'benzina'
    ],
    [
        'id_auto' => 4,
        'codice_telaio' => 'Z7E4AJVVTY9BLEUPG',
        'marca' => 'Jaguar',
        'modello' => 'F-type',
        'numero_porte' => 5,
        'cilindrata' => 2.8,
        'targa' => 'AS867SH',
        'km' => 65087,
        'anno' => 2019,
        'costo' => '43500',
        'colore' => 'rossa',
        'kilowatt' => 300,
        'peso' => 1678,
        'patente' => 'B',
        'foto' => 'https://cdnwp.dealerk.com/d4748478/uploads/sites/26/2021/04/jag_f-type_22my_p300_r-dynamic_black_convertible_exterior-e1618913956453.jpg',
        'carburante' => 'benzina'
    ],
    [
        'id_auto' => 5,
        'codice_telaio' => 'ATWPAZLI8BS6AB9L0',
        'marca' => 'Volkswagen',
        'modello' => 'Tiguan',
        'numero_porte' => 5,
        'cilindrata' => 1.4,
        'targa' => 'DF543DN',
        'km' => 140004,
        'anno' => 2018,
        'costo' => 13452,
        'colore' => 'bianca',
        'kilowatt' => 148,
        'peso' => 1930,
        'patente' => 'B',
        'foto' => 'https://immagini.alvolante.it/sites/default/files/styles/anteprima_lunghezza_640_jpg/public/serie_auto_galleria/2016/02/vw_tiguan_top_ant.png?itok=qiBGGxC3',
        'carburante' => 'ibrida'
    ],
    [
        'id_auto' => 6,
        'codice_telaio' => 'YTSDJSGP342JQA9AK',
        'marca' => 'Renaut',
        'modello' => 'Captur',
        'numero_porte' => 5,
        'cilindrata' => 1.5,
        'targa' => 'AS345DS',
        'km' => 134543,
        'anno' => 2015,
        'costo' => 13245,
        'colore' => 'bianca',
        'kilowatt' => 136,
        'peso' => 1876,
        'patente' => 'B',
        'foto' => 'https://cdn.group.renault.com/ren/it/promozioni/gennaio/captur-hybrid.jpg.ximg.xsmall.jpg/154f18b563.jpg',
        'carburante' => 'diesel'
    ],
    [
        'id_auto' => 7,
        'codice_telaio' => 'A7F1OI24FB1XX0RWE',
        'marca' => 'Skoda',
        'modello' => 'Karoq',
        'numero_porte' => 5,
        'cilindrata' => 1.3,
        'targa' => 'SD456DR',
        'km' => 123231,
        'anno' => 2018,
        'costo' => 14656,
        'colore' => 'arancione',
        'kilowatt' => 140,
        'peso' => 1876,
        'patente' => 'B',
        'foto' => 'https://cdn.motor1.com/images/mgl/8AnpX3/s3/2022-skoda-karoq-style.jpg',
        'carburante' => 'diesel'
    ],
    [
        'id_auto' => 8,
        'codice_telaio' => 'XS53228DEHQEBKX45',
        'marca' => 'Maserati',
        'modello' => 'Levante',
        'numero_porte' => 5,
        'cilindrata' => 2.7,
        'targa' => 'AS456BC',
        'km' => 102123,
        'anno' => 2017,
        'costo' => 64500,
        'colore' => 'blue',
        'kilowatt' => 23,
        'peso' => 1865,
        'patente' => 'B',
        'foto' => 'https://cdn.drivek.it/configurator-imgs/cars/it/800/MASERATI/LEVANTE/40002_SUV-5-PORTE/maserati-levante-2021-side-front.jpg',
        'carburante' => 'benzina'
    ],
];

?>

